### ISSUE TITLE
유튜브 광고 제거도 가능하나요?

### ISSUE THREAD

**Issue by Yangeok** [rationality6/pihole_seoul#1]

**Comment by rationality6** [comment]
영상이 아닌 배너, 썸네일 등은 제거됩니다. 광고 영상은 계속 주소가 변해서 불가능합니다.

**Comment by Yangeok** [comment]
> 영상이 아닌 배너, 썸네일 등은 제거됩니다. 광고 영상은 계속 주소가 변해서 불가능합니다.

감사합니다 :)
