### ISSUE TITLE
아이폰용 trust dns 대체 어플은 없나요

### ISSUE THREAD

**Issue by lth1436** [rationality6/pihole_seoul#2]
항상 감사드립니다. 이전까지는 잘 사용했었는데 이번에 아이폰 12mini로 변경 후 trust dns 사용하면 인터넷 연결이 아예 끊겨버립니다. 혹시 방법이 있는지 문의드립니다.

**Comment by rationality6** [comment]
사용자분이 계셨군요 ㅠㅠ, 제가 감사합니다.
가끔 그냥 막 도커 위에 올린다고 하루 장애 생긴적도 있었는데, 찔리네요.
제가 쓰는 핸드폰은 아이폰7 플러스에, trust dns 를 사용하고 있습니다.
저희 가족이 항상 잘 쓰고 있는 서버라서, 53 번 dns 포트만 엑세스 가능하시면, 문제는 없을꺼 같은데 저도 아는 앱이 없어서 추천드리긴, 잘 몰라서요. 어떤 어플을 사용하셔도 좋을꺼 같습니다! 감사합니다.

**Comment by rationality6** [comment]
혹시해서 아이피가 변경되었는데 확인해보셨나요?

**Comment by rationality6** [comment]
cloasing
